name: CI Retrain Model

on: [push]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: "3.9"

      # Set up conda environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Verify conda
        run: conda --version

      - name: Install dependency
        run: |
          pip install scikit-learn pandas numpy

      - name: Install MLflow
        run: |
          pip install --upgrade "mlflow>=2.9.0"
          
      - name: Run MLflow Project
        run: |
          mlflow run MLProject

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/

      - name: Debug Docker secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN EXISTS"
          fi          

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker Image with MLflow
        run: |
          mlflow build-docker \
            --name ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow \
            MLProject

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow
