name: CI Retrain Model

on: [push]

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: "3.9"

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Verify conda
        run: conda --version

      - name: Install dependency
        run: |
          pip install mlflow scikit-learn pandas numpy

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local 

      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/

      - name: Debug Docker secrets
        run: |
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN EXISTS"
          fi          
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker Image with MLflow
        run: |
          mlflow models build-docker \
            --name ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/workflow-ci-mlflow